import 'package:get/get.dart';
import '../data/constants/string_constants.dart';

class LanguageTranslate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          StringConstants.login: StringConstants.login,
          StringConstants.signUp: StringConstants.signUp,
          StringConstants.logout: StringConstants.logout,
          StringConstants.yes: StringConstants.yes,
          StringConstants.no: StringConstants.no,
          StringConstants.or: StringConstants.or,
          StringConstants.and: StringConstants.and,
          StringConstants.next: StringConstants.next,
          StringConstants.address: StringConstants.address,
          StringConstants.wouldYouLikeToLogout:
              StringConstants.wouldYouLikeToLogout,
          StringConstants.enterYourEmailAndPassword:
              StringConstants.enterYourEmailAndPassword,
          StringConstants.whatYourPhoneNumber:
              StringConstants.whatYourPhoneNumber,
          StringConstants.weSendYouACodeToVerifyIt:
              StringConstants.weSendYouACodeToVerifyIt,
          StringConstants.emailAddress: StringConstants.emailAddress,
          StringConstants.password: StringConstants.password,
          StringConstants.phoneNumber: StringConstants.phoneNumber,
          StringConstants.continueText: StringConstants.continueText,
          StringConstants.updateNow: StringConstants.updateNow,
          StringConstants.skip: StringConstants.skip,
          StringConstants.forgotYourPassword:
              StringConstants.forgotYourPassword,
          StringConstants.dotHaveAnAccount: StringConstants.dotHaveAnAccount,
          StringConstants.signInWithGoogle: StringConstants.signInWithGoogle,
          StringConstants.alreadyRegistered: StringConstants.alreadyRegistered,
          StringConstants.letsGetStartedByCreatingYourAccount:
              StringConstants.letsGetStartedByCreatingYourAccount,
          StringConstants.fullName: StringConstants.fullName,
          StringConstants.mobileNumber: StringConstants.mobileNumber,
          StringConstants.iAgreeToTheAmuse: StringConstants.iAgreeToTheAmuse,
          StringConstants.termsOfService: StringConstants.termsOfService,
          StringConstants.privacyPolicy: StringConstants.privacyPolicy,
          StringConstants.passwordReset: StringConstants.passwordReset,
          StringConstants.pleasePutYourMobileNumberToResetYourPassword:
              StringConstants.pleasePutYourMobileNumberToResetYourPassword,
          StringConstants.sms: StringConstants.sms,
          StringConstants.email: StringConstants.email,
          StringConstants.hintNumber: StringConstants.hintNumber,
          StringConstants.hintEmail: StringConstants.hintEmail,
          StringConstants.submit: StringConstants.submit,
          StringConstants.createNewPassword: StringConstants.createNewPassword,
          StringConstants.yourNewPasswordMustBeDifferentFromPrevious:
              StringConstants.yourNewPasswordMustBeDifferentFromPrevious,
          StringConstants.pleasePutThe4DigitsSentToYou:
              StringConstants.pleasePutThe4DigitsSentToYou,
          StringConstants.enterTheVerificationCode:
              StringConstants.enterTheVerificationCode,
          StringConstants.didNotReceiveTheCode:
              StringConstants.didNotReceiveTheCode,
          StringConstants.save: StringConstants.save,
          StringConstants.pleasePutThe4DigitsSendToYou:
              StringConstants.pleasePutThe4DigitsSendToYou,
          StringConstants.checkYourMailCheckYourCellPhone:
              StringConstants.checkYourMailCheckYourCellPhone,
          StringConstants.newPassword: StringConstants.newPassword,
          StringConstants.confirmPassword: StringConstants.confirmPassword,
          StringConstants.verifyIdentity: StringConstants.verifyIdentity,
          StringConstants.select: StringConstants.select,
          StringConstants.verificationCodeConfirmation:
              StringConstants.verificationCodeConfirmation,
          StringConstants
                  .provideAPhotoOfYouHoldingTheVerificationTheVerification:
              StringConstants
                  .provideAPhotoOfYouHoldingTheVerificationTheVerification,
          StringConstants.home: StringConstants.home,
          StringConstants.explore: StringConstants.explore,
          StringConstants.favorites: StringConstants.favorites,
          StringConstants.friends: StringConstants.friends,
          StringConstants.chats: StringConstants.chats,
          StringConstants.profile: StringConstants.profile,
          StringConstants.messages: StringConstants.messages,
          StringConstants.search: StringConstants.search,
          StringConstants.activities: StringConstants.activities,
          StringConstants.post: StringConstants.post,
          StringConstants.newPost: StringConstants.newPost,
          StringConstants.gallery: StringConstants.gallery,
          StringConstants.writeACaption: StringConstants.writeACaption,
          StringConstants.selectLocation: StringConstants.selectLocation,
          StringConstants.addLocation: StringConstants.addLocation,
          StringConstants.location: StringConstants.location,
          StringConstants.editProfile: StringConstants.editProfile,
          StringConstants.dob: StringConstants.dob,
          StringConstants.gender: StringConstants.gender,
          StringConstants.update: StringConstants.update,
          StringConstants.setting: StringConstants.setting,
          StringConstants.closeFriends: StringConstants.closeFriends,
          StringConstants.passwordChange: StringConstants.passwordChange,
          StringConstants.saved: StringConstants.saved,
          StringConstants.review: StringConstants.review,
          StringConstants.termsAndCondition: StringConstants.termsAndCondition,
          StringConstants.contactUs: StringConstants.contactUs,
          StringConstants.fAQs: StringConstants.fAQs,
          StringConstants.allFieldsRequired: StringConstants.allFieldsRequired,
          StringConstants.searchHistory: StringConstants.searchHistory,
          StringConstants.topCategories: StringConstants.topCategories,
          StringConstants.hotCircle: StringConstants.hotCircle,
          StringConstants.popularQA: StringConstants.popularQA,
          StringConstants.seeAll: StringConstants.seeAll,
          StringConstants.delete: StringConstants.delete,
          StringConstants.deleteAccount: StringConstants.deleteAccount,
          StringConstants.wouldYouLikeToDeleteAccount:
              StringConstants.wouldYouLikeToDeleteAccount,
          StringConstants.notifications: StringConstants.notifications,
          StringConstants.currentPassword: StringConstants.currentPassword,
          StringConstants.changePassword: StringConstants.changePassword,
          StringConstants.language: StringConstants.language,
          StringConstants.payment: StringConstants.payment,
          StringConstants.linkedAccount: StringConstants.linkedAccount,
          StringConstants.support: StringConstants.support,
          StringConstants.faq: StringConstants.faq,
          StringConstants.aboutUs: StringConstants.aboutUs,
          StringConstants.aboutEvent: StringConstants.aboutEvent,
          StringConstants.upload: StringConstants.upload,
          StringConstants.allEvent: StringConstants.allEvent,
          StringConstants.camera: StringConstants.camera,
          StringConstants.typeHere: StringConstants.typeHere,
          StringConstants.chooseImageFromTheOptionsBelow:
              StringConstants.chooseImageFromTheOptionsBelow,
          StringConstants.selectImage: StringConstants.selectImage,
          StringConstants.message: StringConstants.message,
          StringConstants.exitApp: StringConstants.exitApp,
          StringConstants.doYouWantToExitTheApp:
              StringConstants.doYouWantToExitTheApp,
          StringConstants.upgradeToPremium: StringConstants.upgradeToPremium,
          StringConstants.firstName: StringConstants.firstName,
          StringConstants.lastName: StringConstants.lastName,
          StringConstants.welcome: StringConstants.welcome,
          StringConstants.restaurant: StringConstants.restaurant,
          StringConstants.popularEvent: StringConstants.popularEvent,
          StringConstants.allPopularEvent: StringConstants.allPopularEvent,
          StringConstants.featured: StringConstants.featured,
          StringConstants.moreEventsLikeThis:
              StringConstants.moreEventsLikeThis,
          StringConstants.galleryPreEvent: StringConstants.galleryPreEvent,
          StringConstants.allFeatured: StringConstants.allFeatured,
          StringConstants.english: StringConstants.english,
          StringConstants.german: StringConstants.german,
          StringConstants.facebook: StringConstants.facebook,
          StringConstants.google: StringConstants.google,
          StringConstants.apple: StringConstants.apple,
          StringConstants.change: StringConstants.change,
          StringConstants.enableLocation: StringConstants.enableLocation,
          StringConstants.resetOtp: StringConstants.resetOtp,
          StringConstants.cancel: StringConstants.cancel,
          StringConstants.addEvent: StringConstants.addEvent,
          StringConstants.eventName: StringConstants.eventName,
          StringConstants.date: StringConstants.date,
          StringConstants.time: StringConstants.time,
          StringConstants.photo: StringConstants.photo,
          StringConstants.publish: StringConstants.publish,
          StringConstants.myPublishedEvent: StringConstants.myPublishedEvent,
          StringConstants.reviewSummary: StringConstants.reviewSummary,
          StringConstants.edit: StringConstants.edit,
          StringConstants.tax: StringConstants.tax,
          StringConstants.total: StringConstants.total,
          StringConstants.subscription: StringConstants.subscription,
          StringConstants.subscriptionCharge:
              StringConstants.subscriptionCharge,
          StringConstants.updateToPremium: StringConstants.updateToPremium,
          StringConstants.selectCategory: StringConstants.selectCategory,
          StringConstants.removeAllFilter: StringConstants.removeAllFilter,
          StringConstants.congratulations: StringConstants.congratulations,
          StringConstants.eventImage: StringConstants.eventImage,
          StringConstants.premiumSubscription:
              StringConstants.premiumSubscription,
          StringConstants.normalSubscription:
              StringConstants.normalSubscription,
          StringConstants.descriptionLink: StringConstants.descriptionLink,
          StringConstants.chatGpt: StringConstants.chatGpt,
          StringConstants.friend: StringConstants.friend,
          StringConstants.event: StringConstants.event,
          StringConstants.onlyOneTime: StringConstants.onlyOneTime,
          StringConstants.monthly: StringConstants.monthly,
          StringConstants.weekly: StringConstants.weekly,
          StringConstants.yearly: StringConstants.yearly,
          StringConstants.enterText: StringConstants.enterText,
          StringConstants.follow: StringConstants.follow,
          StringConstants.eventRecurring: StringConstants.eventRecurring,
          StringConstants.eventVisibleFrom: StringConstants.eventVisibleFrom,
          StringConstants.pleaseUpdateYourSubscriptionPlanForAdvanceFeatures:
              StringConstants
                  .pleaseUpdateYourSubscriptionPlanForAdvanceFeatures,
          StringConstants.youHaveSuccessfullyPurchasedPlanEnjoyTheEvent:
              StringConstants.youHaveSuccessfullyPurchasedPlanEnjoyTheEvent,
          StringConstants.doYouWantDeleteSearchHistory:
              StringConstants.doYouWantDeleteSearchHistory,
          StringConstants.coverPhoto: StringConstants.coverPhoto
        },
        'de_Us': {
          StringConstants.login: 'Anmeldung',
          StringConstants.signUp: 'Melden Sie sich an',
          StringConstants.logout: 'Ausloggen',
          StringConstants.yes: 'Ja',
          StringConstants.no: 'NEIN',
          StringConstants.or: 'oder',
          StringConstants.and: 'Und',
          StringConstants.next: 'nächste',
          StringConstants.address: 'Adresse',
          StringConstants.wouldYouLikeToLogout: 'Möchten Sie sich abmelden?',
          StringConstants.enterYourEmailAndPassword:
              'Geben Sie Ihre E-Mail-Adresse und Ihr Passwort ein',
          StringConstants.whatYourPhoneNumber: 'Wie ist deine Telefonnummer?',
          StringConstants.weSendYouACodeToVerifyIt:
              'Wir senden Ihnen einen Code zur Überprüfung',
          StringConstants.emailAddress: 'Email Address ',
          StringConstants.password: 'passwort',
          StringConstants.phoneNumber: 'Telefonnummer',
          StringConstants.continueText: 'Weitermachen',
          StringConstants.updateNow: 'JETZT AKTUALISIEREN',
          StringConstants.skip: 'Überspringen',
          StringConstants.forgotYourPassword:
              'Haben Sie Ihr Passwort vergessen?',
          StringConstants.dotHaveAnAccount: 'Sie haben kein Konto? ',
          StringConstants.signInWithGoogle: 'Anmeldung mit Google',
          StringConstants.alreadyRegistered: 'Sie haben bereits ein Konto?',
          StringConstants.letsGetStartedByCreatingYourAccount:
              'Beginnen wir mit der Erstellung Ihres Kontos',
          StringConstants.fullName: 'Vollständiger Name',
          StringConstants.mobileNumber: 'Handynummer',
          StringConstants.iAgreeToTheAmuse: 'Ich stimme dem Amuse zu',
          StringConstants.termsOfService: 'Nutzungsbedingungen',
          StringConstants.privacyPolicy: 'Datenschutzrichtlinie',
          StringConstants.passwordReset: 'Passwort zurücksetzen',
          StringConstants.pleasePutYourMobileNumberToResetYourPassword:
              'Bitte geben Sie Ihre Handynummer ein, um Ihr Passwort zurückzusetzen',
          StringConstants.sms: 'SMS',
          StringConstants.email: 'Email',
          StringConstants.hintNumber: '+91 8********7',
          StringConstants.hintEmail: 'joh*******@gmail.com',
          StringConstants.submit: 'Einreichen',
          StringConstants.createNewPassword: 'Neues Passwort erstellen',
          StringConstants.yourNewPasswordMustBeDifferentFromPrevious:
              'Ihr neues Passwort muss sich von den zuvor verwendeten Passwörtern unterscheiden.',
          StringConstants.pleasePutThe4DigitsSentToYou:
              'Bitte geben Sie die Ihnen zugesandten 4 Ziffern ein',
          StringConstants.enterTheVerificationCode:
              'Geben Sie den Bestätigungscode ein',
          StringConstants.didNotReceiveTheCode:
              'Sie haben den Code nicht erhalten?',
          StringConstants.save: 'Speichern',
          StringConstants.pleasePutThe4DigitsSendToYou:
              'Bitte geben Sie die 4 Ziffern ein, die Sie erhalten haben',
          StringConstants.checkYourMailCheckYourCellPhone:
              'Überprüfen Sie Ihre E-Mails oder Ihr Mobiltelefon',
          StringConstants.newPassword: 'Neues Kennwort',
          StringConstants.confirmPassword: 'Bestätige das Passwort',
          StringConstants.verifyIdentity: 'Identität überprüfen',
          StringConstants.select: 'Wählen',
          StringConstants.verificationCodeConfirmation:
              'Bestätigung des Bestätigungscodes',
          StringConstants
                  .provideAPhotoOfYouHoldingTheVerificationTheVerification:
              'Stellen Sie ein Foto bereit, auf dem Sie den unten angezeigten Bestätigungscode in einer Hand und Ihren Ausweis deutlich sichtbar in der anderen Hand halten',
          StringConstants.home: 'Heim',
          StringConstants.explore: 'Erkunden',
          StringConstants.favorites: 'Favoriten',
          StringConstants.friends: 'Freunde',
          StringConstants.chats: 'Chats',
          StringConstants.profile: 'Profil',
          StringConstants.messages: 'Mitteilungen',
          StringConstants.search: 'Suchen',
          StringConstants.activities: 'Aktivitäten',
          StringConstants.post: 'Post',
          StringConstants.newPost: 'New Post',
          StringConstants.gallery: 'Galerie',
          StringConstants.writeACaption: 'Schreibe eine Überschrift',
          StringConstants.selectLocation: 'Ort auswählen',
          StringConstants.addLocation: 'Ort hinzufügen',
          StringConstants.location: 'Standort',
          StringConstants.editProfile: 'Profil bearbeiten',
          StringConstants.dob: 'Geburtsdatum',
          StringConstants.gender: 'Geschlecht',
          StringConstants.update: 'Aktualisieren',
          StringConstants.setting: 'Einstellung',
          StringConstants.closeFriends: 'Enge Freunde',
          StringConstants.passwordChange: 'Passwortänderung',
          StringConstants.saved: 'Gerettet',
          StringConstants.review: 'Rezension',
          StringConstants.termsAndCondition: 'Geschäftsbedingung',
          StringConstants.contactUs: 'Kontaktiere uns',
          StringConstants.fAQs: 'FAQs',
          StringConstants.allFieldsRequired: 'Alle Felder benötigt',
          StringConstants.searchHistory: 'Suchverlauf',
          StringConstants.topCategories: 'Top-Kategorien',
          StringConstants.hotCircle: 'Heißer Kreis',
          StringConstants.popularQA: 'Beliebte Fragen und Antworten',
          StringConstants.seeAll: 'Alles sehen',
          StringConstants.delete: 'Löschen',
          StringConstants.deleteAccount: 'Konto löschen',
          StringConstants.wouldYouLikeToDeleteAccount:
              'Möchten Sie Ihr Konto löschen?',
          StringConstants.notifications: 'Benachrichtigungen',
          StringConstants.currentPassword: 'Aktuelles Passwort',
          StringConstants.changePassword: 'Kennwort ändern',
          StringConstants.language: 'Sprache',
          StringConstants.payment: 'Zahlung',
          StringConstants.linkedAccount: 'Verknüpftes Konto',
          StringConstants.support: 'Unterstützung',
          StringConstants.faq: 'FAQ',
          StringConstants.aboutUs: 'Über uns',
          StringConstants.aboutEvent: 'Über Veranstaltung',
          StringConstants.upload: 'HOCHLADEN',
          StringConstants.allEvent: 'Alle Veranstaltungen',
          StringConstants.camera: 'Kamera',
          StringConstants.typeHere: 'Geben Sie hier ein',
          StringConstants.chooseImageFromTheOptionsBelow:
              'Wählen Sie „Bild“ aus den Optionen unten',
          StringConstants.selectImage: 'Bild auswählen',
          StringConstants.message: 'Nachricht',
          StringConstants.exitApp: 'App beenden',
          StringConstants.doYouWantToExitTheApp: 'Möchten Sie die App beenden?',
          StringConstants.upgradeToPremium: 'Auf Premium upgraden',
          StringConstants.firstName: 'Vorname',
          StringConstants.lastName: 'Nachname',
          StringConstants.welcome: 'Willkommen',
          StringConstants.restaurant: 'Restaurant',
          StringConstants.popularEvent: 'Beliebte Veranstaltung',
          StringConstants.allPopularEvent: 'Alle beliebten Veranstaltungen',
          StringConstants.featured: 'Hervorgehoben',
          StringConstants.moreEventsLikeThis:
              'Weitere Veranstaltungen wie diese',
          StringConstants.galleryPreEvent: 'Galerie (Vorveranstaltung)',
          StringConstants.allFeatured: 'Alle vorgestellt',
          StringConstants.english: 'Englisch',
          StringConstants.german: 'Deutsch',
          StringConstants.facebook: 'Facebook',
          StringConstants.google: 'Google',
          StringConstants.apple: 'Apple',
          StringConstants.change: 'Change',
          StringConstants.enableLocation: 'Aktiviere Standort',
          StringConstants.resetOtp: 'ResetOtp',
          StringConstants.cancel: 'Stornieren',
          StringConstants.addEvent: 'Ereignis hinzufügen',
          StringConstants.eventName: 'Veranstaltungsname',
          StringConstants.date: 'Datum',
          StringConstants.time: 'Zeit',
          StringConstants.photo: 'Foto',
          StringConstants.publish: 'Veröffentlichen',
          StringConstants.myPublishedEvent:
              'Meine veröffentlichte Veranstaltung',
          StringConstants.reviewSummary: 'Zusammenfassung',
          StringConstants.edit: 'Bearbeiten',
          StringConstants.tax: 'Steuer',
          StringConstants.total: 'Gesamt',
          StringConstants.subscription: 'Abonnement',
          StringConstants.subscriptionCharge: 'Abonnementgebühr',
          StringConstants.updateToPremium: 'Auf Premium upgraden',
          StringConstants.selectCategory: 'Kategorie wählen',
          StringConstants.removeAllFilter: 'Alle Filter entfernen',
          StringConstants.congratulations: 'Glückwunsch',
          StringConstants.eventImage: 'Ereignisbild',
          StringConstants.premiumSubscription: 'Premium-Abonnement',
          StringConstants.normalSubscription: 'Normales Abonnement',
          StringConstants.descriptionLink: 'Beschreibungslink',
          StringConstants.chatGpt: 'ChatGpt',
          StringConstants.friend: 'Freund',
          StringConstants.event: 'Ereignis',
          StringConstants.onlyOneTime: 'Only one time',
          StringConstants.monthly: 'Monthly',
          StringConstants.weekly: 'Weekly',
          StringConstants.yearly: 'Yearly',
          StringConstants.enterText: 'Text eingeben',
          StringConstants.follow: 'Folgen',
          StringConstants.eventRecurring: 'Wiederkehrendes Ereignis',
          StringConstants.eventVisibleFrom: 'Ereignis sichtbar von',
          StringConstants.pleaseUpdateYourSubscriptionPlanForAdvanceFeatures:
              'Bitte aktualisieren Sie Ihr Abonnement für erweiterte Funktionen.',
          StringConstants.youHaveSuccessfullyPurchasedPlanEnjoyTheEvent:
              'Sie haben den Plan erfolgreich gekauft. Genießen Sie die Veranstaltung!',
          StringConstants.doYouWantDeleteSearchHistory:
              'Möchten Sie den Suchverlauf löschen?',
          StringConstants.coverPhoto: 'Titelbild'
        },
      };
}
